<?php
session_start();
require 'APIs/GoogleAuth/GoogleAuthenticator.php';

$authenticator = new PHPGangsta_GoogleAuthenticator();
//take secret from post
$secret = $_SESSION['googleSecret'];//This is used to generate QR code
$otp = $_POST['code'];//Generated by Authenticator.
$tolerance = 0;
//$oneCode = $ga->getCode($secret);
//echo "Checking Code '$oneCode' and Secret '$secret':\n";

$checkResult = $authenticator->verifyCode($secret, $otp, $tolerance);    
 
if ($checkResult) 
{
    echo 1; //es el correcto
     
} else {
    echo 0; //error
}
?>


 
 

